

title: Pagina Web de PEA2 de E-Business
email: i47517731@isise.edu.pe
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/PEA2_MACHACUAYLUISGUSTAVO" # the subpath of your site, e.g. /blog
url: "https://luisaguilarmachacuay.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: luisAguilar
github_username:  luisAguilarMachacuay

# Build settings
theme: minima
plugins:
  - jekyll-feed


